# Guia de Introdução ao NumPy

NumPy, que significa Numerical Python, é uma biblioteca fundamental para a computação científica em Python. Ela fornece suporte para arrays e matrizes, além de funções matemáticas para operações com esses objetos. É, também, a base da biblioteca Pandas.



## Números aleatórios e estatística básica  

In [2]:
import numpy as np

# Crie um gerador de números aleatórios.
rng = np.random.default_rng()

numero_aleatorio = rng.random()
print(numero_aleatorio)

0.7974512816166494


In [15]:
array_aleatorio = rng.random(3) #quantidade de números aleatórios gerados
print(array_aleatorio)

[0.00728435 0.70474238 0.49028155]


In [16]:
print(array_aleatorio * 10) # por padrão os números gerados são de 0. , quando adicionado um multiplicador está adicionando mais uma casa no número gerado 


[0.07284347 7.04742375 4.90281547]


 Vamos criar um cenário onde esses dados aleatórios podem ser úteis para uma análise de vendas.

Suponha que você seja um analista de vendas em uma empresa e queira entender melhor o desempenho das vendas de um produto específico. No entanto, você não tem acesso aos dados reais de vendas, então você decide gerar alguns dados de vendas aleatórios para realizar sua análise.

In [3]:
# Gere dados de vendas falsos para 30 dias
# Vamos supor que as vendas de um produto podem variar de 50 a 200 por dia 
rng = np.random.default_rng(seed=42) # esse trecho serve para fixar os números aleatórios que foram gerados
dados_vendas = rng.integers(low=50, high=200, size=30)
print(dados_vendas) 

[ 63 166 148 115 114 178  62 154  80  64 128 196 160 164 157 167 126  69
 175 117 125 105  77 189 167 146 110 173 131 116]


In [5]:
#adicionando separador vírgula na lista
dados_formatados = ", ".join(str(x) for x in dados_vendas)
print(dados_formatados)

63, 166, 148, 115, 114, 178, 62, 154, 80, 64, 128, 196, 160, 164, 157, 167, 126, 69, 175, 117, 125, 105, 77, 189, 167, 146, 110, 173, 131, 116


In [31]:
#ordenar os maiores números do array
maiores_valores = np.sort(dados_vendas)[-3:]
print(maiores_valores)

[178 189 196]


In [41]:
#exibindo os dias onde houve as maiores vendas
dias_vendas = np.argsort(dados_vendas)[-3:]
print(dias_vendas)

[ 5 23 11]


Agora, você pode usar esses dados para realizar várias análises. Por exemplo, você pode querer saber qual foi o dia com as vendas mais altas, as vendas mais baixas, ou a média de vendas durante o mês. Aqui está como você pode fazer isso:



In [ ]:
print(np.max(dados_vendas))

196


In [ ]:
print(np.argmax(dados_vendas))

11


In [ ]:
# Dia com as vendas mais altas
vendas_maximas = np.max(dados_vendas)
dia_vendas_maximas = np.argmax(dados_vendas) + 1
print(f"O dia com as vendas mais altas foi o dia {dia_vendas_maximas} com {vendas_maximas} vendas.")

O dia com as vendas mais altas foi o dia 12 com 196 vendas.


In [ ]:
# Dia com as vendas mais baixas
vendas_minimas = np.min(dados_vendas)
dia_vendas_minimas = np.argmin(dados_vendas) + 1
print(f"O dia com as vendas mais baixas foi o dia {dia_vendas_minimas} com {vendas_minimas} vendas.")

O dia com as vendas mais baixas foi o dia 7 com 62 vendas.


In [ ]:
# Média de vendas durante o mês
media_vendas = np.mean(dados_vendas)
print(f"A média de vendas durante o mês foi de {media_vendas} vendas por dia.")


A média de vendas durante o mês foi de 131.4 vendas por dia.


In [ ]:
print(np.median(dados_vendas))

129.5


In [ ]:
print(np.percentile(dados_vendas, 50))

129.5


In [ ]:
print(np.std(dados_vendas))

39.305300745149715


In [ ]:
print(np.var(dados_vendas))


1544.9066666666665


Breve resumo e conceitos simplificados das funções estatísticas citadas:

1. Mediana:
A mediana é um valor que divide um conjunto de dados em duas partes iguais. Para encontrá-la, você deve organizar os dados em ordem crescente ou decrescente e escolher o valor do meio. Se houver um número ímpar de dados, a mediana será exatamente o valor central. Se houver um número par de dados, a mediana será a média dos dois valores do meio.

2. Percentil:
O percentil é uma medida estatística que indica a posição relativa de um dado dentro de um conjunto de dados. Ele informa a porcentagem de valores que estão abaixo desse dado. Por exemplo, o percentil 50 (também conhecido como mediana) divide os dados em duas partes iguais, com 50% dos valores abaixo dele e 50% acima.

3. Desvio padrão:
O desvio padrão é uma medida que indica o quão dispersos os valores de um conjunto de dados estão em relação à média. Ele mostra a variabilidade dos dados em relação ao valor médio. Um desvio padrão maior indica que os dados estão mais espalhados, enquanto um desvio padrão menor indica que os dados estão mais próximos da média.

4. Variância:
A variância é outra medida de dispersão que indica o quão distantes os valores de um conjunto de dados estão da média. Ela é calculada como a média dos quadrados das diferenças entre cada valor e a média. A variância fornece uma medida da dispersão total dos dados, independentemente de serem maiores ou menores que a média.

Essas medidas são amplamente utilizadas na estatística para resumir e analisar conjuntos de dados. Elas fornecem informações valiosas sobre a distribuição, a variabilidade e a posição dos dados, permitindo uma compreensão mais completa dos mesmos.