## Exercício

Você é um analista de RH e tem os salários de todos os funcionários da sua empresa em um array NumPy. Seu trabalho é identificar quantos funcionários ganham acima da média. Use o seguinte array para sua análise: `salarios = np.array([3000, 2500, 3500, 4000, 2000, 4500, 3000, 3800, 4800])`.

In [12]:
import numpy as np

salarios = np.array([3000, 2500, 3500, 4000, 2000, 4500, 3000, 3800, 4800])
media_salarial = np.mean(salarios)
print(media_salarial)

3455.5555555555557


In [ ]:
print(np.where(salarios > media_salarial))

(array([2, 3, 5, 7, 8], dtype=int64),)


In [ ]:
print(salarios[salarios > media_salarial])

[3500 4000 4500 3800 4800]


In [ ]:
print(salarios > media_salarial)

[False False  True  True False  True False  True  True]


In [ ]:
print(np.sum(salarios > media_salarial))

5


In [ ]:
print(True == 1)

True


In [ ]:
print(False == 0)

True


In [ ]:
# funciona com listas e tuplas também
print(sum([True, False, True, False]))
print(sum((True, False, True, False)))

2
2


In [ ]:
funcionarios_acima_media = np.sum(salarios > media_salarial)
print(f"{funcionarios_acima_media} funcionários ganham acima da média salarial.")

5 funcionários ganham acima da média salarial.


### Bônus

Outras formas de fazer contagem

In [ ]:
print(np.count_nonzero(salarios > media_salarial))

5


In [ ]:
print(np.unique(salarios > media_salarial))

[False  True]


In [ ]:
print(np.unique(salarios > media_salarial, return_counts=True))

(array([False,  True]), array([4, 5], dtype=int64))


In [ ]:
valores_unicos, contagem = np.unique(salarios > media_salarial, return_counts=True)
print(valores_unicos)
print(contagem)

[False  True]
[4 5]


### Bônus 2

Criando 20 valores fictícios de salários com a mesma faixa anterior, tomando cuidado de outras pessoas gerarem os mesmos valores:

In [14]:
rng = np.random.default_rng(seed=42)

salarios_gerados = rng.integers(low=np.min(salarios), high=np.max(salarios), size=20)
print(salarios_gerados)

[2249 4167 3832 3228 3212 4404 2240 3952 2564 2263 3474 4731 4060 4131
 4008 4200 3437 2358 4351 3261]


In [15]:
media = np.mean(salarios_gerados)
print(media)

3506.1


In [17]:
num_acima_media = np.sum(salarios_gerados > media)
print(num_acima_media)

10


In [ ]:
rng = np.random.default_rng(seed=42)

salarios_gerados = rng.integers(low=np.min(salarios), high=np.max(salarios), size=20, endpoint=True)
print(salarios_gerados)

[2249 4167 3833 3229 3212 4404 2240 3953 2564 2263 3474 4732 4060 4131
 4009 4201 3437 2358 4352 3261]


In [ ]:
print(np.mean(salarios_gerados))

3506.45


In [ ]:
# as funções estatísticas também podem ser chamadas como métodos dos arrays
print(salarios_gerados.min())
print(salarios_gerados.max())
print(salarios_gerados.mean())

2240
4732
3506.45
