Considere que uma loja funciona de segunda a sábado, independetemente de feriados. Nos últimos 30 dias, teve o menos volume de vendas sedo 20 e o maior sendo 200. Crie uma simulação das vendas desses ´ltimos 30 dias, separando por semanas.
calcule:
- o total de vendas por semana
- a média de vendas por semana
- a média de vendas por dia da semana

In [ ]:
#gerando tabela de vendas hipotéticas do mês
import numpy as np
rng = np.random.default_rng(seed=0)
vendas = np.array(rng.integers(low=20, high=200, size=30, endpoint=True))# o endpoint inclui o valor máximo, que no caso é 200
print(vendas)

[173 135 112  68  75  27  33  22  51 167 137 185 111 129 195 152 134 118
 121 189  70 167 141  20  91 175 120  26 158 152]


In [15]:
#separando o mês em 6 semanas de 5 dias cada
semanas = vendas.reshape(5,6)
print(semanas)

[[173 135 112  68  75  27]
 [ 33  22  51 167 137 185]
 [111 129 195 152 134 118]
 [121 189  70 167 141  20]
 [ 91 175 120  26 158 152]]


In [16]:
#tota de vendas por semana
print(semanas.sum(axis=1))


[590 595 839 708 722]


In [17]:
#média de vendas por semana
print(semanas.mean(axis=1))

[ 98.33333333  99.16666667 139.83333333 118.         120.33333333]


In [18]:
#média de vendas por dia da semana
print(semanas.mean(axis=0))

[105.8 130.  109.6 116.  129.  100.4]
